// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe2y6H6zo6G3n7UUI9N47dl0CFGfjxqf0',
    appId: '1:833206345542:web:ae314986ae4c774f168f47',
    messagingSenderId: '833206345542',
    projectId: 'ooriba-s3-ad808',
    authDomain: 'ooriba-s3-ad808.firebaseapp.com',
    storageBucket: 'ooriba-s3-ad808.appspot.com',
    measurementId: 'G-VKY2XMVSF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkYktmjYyPB_aKRGVTjKLB2aDw0DbJGy4',
    appId: '1:833206345542:android:46e7b7bca0e5d5a2168f47',
    messagingSenderId: '833206345542',
    projectId: 'ooriba-s3-ad808',
    storageBucket: 'ooriba-s3-ad808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3nEtxNnjxBgcp6Olaj60YSjAUjrOXQ48',
    appId: '1:833206345542:ios:69e897fe2f9e61a7168f47',
    messagingSenderId: '833206345542',
    projectId: 'ooriba-s3-ad808',
    storageBucket: 'ooriba-s3-ad808.appspot.com',
    iosBundleId: 'com.example.ooriba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3nEtxNnjxBgcp6Olaj60YSjAUjrOXQ48',
    appId: '1:833206345542:ios:69e897fe2f9e61a7168f47',
    messagingSenderId: '833206345542',
    projectId: 'ooriba-s3-ad808',
    storageBucket: 'ooriba-s3-ad808.appspot.com',
    iosBundleId: 'com.example.ooriba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe2y6H6zo6G3n7UUI9N47dl0CFGfjxqf0',
    appId: '1:833206345542:web:35232248d5c95e45168f47',
    messagingSenderId: '833206345542',
    projectId: 'ooriba-s3-ad808',
    authDomain: 'ooriba-s3-ad808.firebaseapp.com',
    storageBucket: 'ooriba-s3-ad808.appspot.com',
    measurementId: 'G-Z2BZ8LFF5K',
  );
}
